.deploy:
  image: registry.gitlab.b-data.ch/r/verse
  stage: deploy
  variables:
    CRAN: "https://stat.ethz.ch/CRAN/"
    GIT_DEPTH: "1"

pages:
  extends: .deploy
  script:
  - >
    echo "options(repos = c(CRAN='$CRAN'), download.file.method = 'libcurl')"
    > /usr/local/lib/R/etc/Rprofile.site
  - apt update
  - apt-get install -y --no-install-recommends libudunits2-dev librsvg2-dev
  - Rscript -e "install.packages(c('pkgdown', 'quarto'))"
  - Rscript -e "install.packages(c('dplyr', 'tidyr', 'units', 'rlang'))"
  - Rscript -e "install.packages(c('remotes'))"
  - Rscript -e "remotes::install_version('DiagrammeR', version = '1.0.11')"
  - Rscript -e "install.packages(c('dm', 'DiagrammeRsvg', 'DT', 'RefManageR'))"
  - Rscript -e "install.packages('chents', repos = c('https://jranke.r-universe.dev', 'https://cloud.r-project.org'))"
  - Rscript -e "install.packages('srppphist', repos = c('https://agroscope-ch.r-universe.dev', 'https://cloud.r-project.org'))"
  - Rscript -e "install.packages('roxygen2', repos = c('https://r-lib.r-universe.dev', 'https://cloud.r-project.org'))"
  - R CMD INSTALL .
  - Rscript -e "pkgdown::build_site(quiet = FALSE)"
  - mv docs public
  - >
    find public -type f -regex '.*\.\(htm\|html\|txt\|text\|js\|css\|ico\)$'
    -exec gzip -f -k {} \;
  artifacts:
    paths:
    - public
  rules:
    - if: $CI_COMMIT_REF_NAME == "main"
