species_in <- tribble(~species, ~group,
  "Pagrus major", "Fish",
  "Jordanella floridae", "Fish",
  "Menidia beryllina", "Fish",
  "Gambusia holbrooki", "Fish",
  "Oreochromis mossambicus", "Fish",
  "Leiostomus xanthurus", "Fish",
  "Oncorhynchus mykiss", "Fish",
  "Lepomis macrochirus", "Fish",
  "Cyprinodon variegatus", "Fish",
  "Pimephales promelas", "Fish",
  "Danio rerio", "Fish",
  "Cyprinus carpio", "Fish",
  "Perca fluviatilis", "Fish",
  "Pimephales notatus", "Fish",
  "Salvelinus fontinalis", "Fish",
  "Oncorhynchus kisutch", "Fish",
  "Ictalurus punctatus", "Fish",
  "Barbatula barbatula", "Fish",
  "Catostomus commersonii", "Fish",
  "Esox lucius", "Fish",
  "Acipenser transmontanus", "Fish",
  "Leuciscus idus", "Fish",
  "Gasterosteus aculeatus", "Fish",
  "Oryzias latipes", "Fish",
  "Poecilia reticulata", "Fish",
  "Salmo gairdneri", "Fish",
  "Salmo trutta", "Fish",
  "Brachydanio rerio", "Fish",
  "Xenopus laevis", "Amphibians",
  "Ctenodrilus serratus", "Aquatic invertebrates",
  "Chironomus yoshimatsui", "Aquatic invertebrates",
  "Ceriodaphnia sp.", "Aquatic invertebrates",
  "Palaemon kadiakensis", "Aquatic invertebrates",
  "Chironomus tentans", "Aquatic invertebrates",
  "Macrocyclops fuscus", "Aquatic invertebrates",
  "Daphnia magna", "Aquatic invertebrates",
  "Chironomus riparius", "Aquatic invertebrates",
  "Gammarus fasciatus", "Aquatic invertebrates",
  "Mysidopsis bahia", "Aquatic invertebrates",
  "Gammarus pulex", "Aquatic invertebrates",
  "Simulium latigonium", "Aquatic invertebrates",
  "Metacarcinus magister", "Aquatic invertebrates",
  "Mercenaria mercenaria", "Aquatic invertebrates",
  "Procambarus acutus acutus", "Aquatic invertebrates",
  "Amphiascus tenuiremis", "Aquatic invertebrates",
  "Leptocheirus plumulosus", "Aquatic invertebrates",
  "Chaoborus crystallinus", "Aquatic invertebrates",
  "Daphnia longispina", "Aquatic invertebrates",
  "Daphnia pulex", "Aquatic invertebrates",
  "Simocephalus sp.", "Aquatic invertebrates",
  "Brachionus calyciflorus", "Aquatic invertebrates",
  "Thamnocephalus platyurus", "Aquatic invertebrates",
  "Chaoborus sp.", "Aquatic invertebrates",
  "Gammarus sp.", "Aquatic invertebrates",
  "Gammarus pseudolimnaeus", "Aquatic invertebrates",
  "Lymnaea stagnalis", "Aquatic invertebrates",
  "Eudiaptomus graciloides", "Aquatic invertebrates",
  "Cyclops sp.", "Aquatic invertebrates",
  "Hyalella azteca", "Aquatic invertebrates",
  "Cloeon dipterum", "Aquatic invertebrates",
  "Corixa sp.", "Aquatic invertebrates",
  "Hydracarina", "Aquatic invertebrates",
  "Ischnura elegans", "Aquatic invertebrates",
  "Ostracoda", "Aquatic invertebrates",
  "Palaemonetes pugio", "Aquatic invertebrates",
  "Lampsilis siliquoidea", "Aquatic invertebrates",
  "Tigriopus japonicus", "Aquatic invertebrates",
  "Ceriodaphnia dubia", "Aquatic invertebrates",
  "Crassostrea virginica", "Aquatic invertebrates",
  "Americamysis bahia", "Aquatic invertebrates",
  "Scenedesmus subspicatus", "Aquatic algae",
  "Scenedesmus quadricauda", "Aquatic algae",
  "Scenedesmus pannonicus", "Aquatic algae",
  "Nitzschia palea", "Aquatic algae",
  "Pseudokirchneriella subcapitata", "Aquatic algae",
  "Desmodesmus subspicatus", "Aquatic algae",
  "Navicula pelliculosa",  "Aquatic algae",
  "Skeletonema costatum",  "Aquatic algae",
  "Raphidocelis subcapitata", "Aquatic algae",
  "Selenastrum capricornutum", "Aquatic algae",
  "Chlorella pyrenoidosa", "Aquatic algae",
  "Chlorella vulgaris", "Aquatic algae",
  "Synechococcus leopoliensis", "Aquatic cyanobacteria",
  "Dolichospermum flos-aquae", "Aquatic cyanobacteria",
  "Anabaena variabilis", "Aquatic cyanobacteria",
  "Aphanizomenon flos-aquae", "Aquatic cyanobacteria",
  "Microcystis aeruginosa", "Aquatic cyanobacteria",
  "Lemna gibba", "Aquatic macrophytes",
  "Myriophyllum spicatum", "Aquatic macrophytes",
  "Vallisneria americana", "Aquatic macrophytes",
  "Myriophyllum aquaticum", "Aquatic macrophytes",
  "Lemna minor", "Aquatic macrophytes",
  "Elodea canadensis", "Aquatic macrophytes",
  "Ceratophyllum demersum", "Aquatic macrophytes",
  "Cabomba caroliniana", "Aquatic macrophytes",
  "Glyceria fluitans", "Aquatic macrophytes",
  "Eisenia fetida", "Soil fauna",
  "Eisenia andrei", "Soil fauna",
  "Hypoaspis aculeifer", "Soil fauna",
  "Folsomia candida", "Soil fauna",
  "Enchytraeus albidus", "Soil fauna",
  "Enchytraeus crypticus", "Soil fauna",
  "Steinernema carpocapsae", "Soil fauna",
  "Chironomus sp.", "Aquatic invertebrates",
  "Myriophyllum sp.", "Aquatic macrophytes",
  "Chlamydomonas terricola", "Aquatic algae",
  "Ankistrodesmus falcatus", "Aquatic algae",
  "Closterium cornu", "Aquatic algae",
  "Xanthonema debile", "Aquatic algae",
  "Chara globularis", "Aquatic macrophytes",
  "Planorbella trivolvis", "Aquatic invertebrates",
  "Nasturtium officinale", "Aquatic macrophytes",
  "Cyclopoida", "Aquatic invertebrates",
  "Chydorus sphaericus", "Aquatic invertebrates",
  "Physa acuta", "Aquatic invertebrates",
  "Simocephalus vetulus", "Aquatic invertebrates",
  "Procambarus clarkii", "Aquatic invertebrates",
  "Salmo salar", "Fish",
  "Ranunculus aquatilis", "Aquatic macrophytes",
  "Glyceria maxima", "Aquatic macrophytes",
  "Elodea densa", "Aquatic macrophytes",
  "Egeria densa", "Aquatic macrophytes",
  "Chlamydomonas noctigama", "Aquatic algae",
  "Palaemon pugio", "Aquatic invertebrates",
  "Fistulifera pelliculosa", "Aquatic algae",
  "Daphniopsis sp.", "Aquatic invertebrates",
  "Cloeon sp.", "Aquatic invertebrates",
  "Asellus aquaticus", "Aquatic invertebrates",
  "Crassostrea gigas", "Aquatic invertebrates",

  )
