species_synonyms <- tribble(~synonym, ~species,
  "Thamnocephalus platyururs", "Thamnocephalus platyurus",
  "Anabaena flosaquae", "Dolichospermum flos-aquae",
  "Anabaena flos-aquae", "Dolichospermum flos-aquae",
  "Palaemonetes kadlakensis" , "Palaemon kadiakensis",
  "Lepomis macrochiris", "Lepomis macrochirus",
  "Brachidanio rerio", "Brachydanio rerio",
  "Tigriopus japonicas", "Tigriopus japonicus",
  "Oncorrynchus mykiss", "Oncorhynchus mykiss",
  "Onchorhynchus mykiss", "Oncorhynchus mykiss",
  "Guppy", "Poecilia reticulata",
  "Oncorynchus mykiss", "Oncorhynchus mykiss",
  "Gammerus pulex", "Gammarus pulex",
  "Salmo gairdnerii", "Salmo gairdneri",
  "Lampsilis siliquiidea", "Lampsilis siliquoidea",
  "Neomacheilus barbatulus", "Barbatula barbatula",
  "Daphnia longispona", "Daphnia longispina",
  "Brachionus calciflorus", "Brachionus calyciflorus",
  "Eurasian watermilfoil", "Myriophyllum spicatum",
  "Wild celery", "Vallisneria americana",
  "Water celery", "Vallisneria americana",
  "Parrot feather", "Myriophyllum aquaticum",
  "Common duckweed", "Lemna minor",
  "Swollen duckweed", "Lemna gibba",
  "S. capricornutum", "Pseudokirchneriella subcapitata",
  "P. subcapitata", "Pseudokirchneriella subcapitata",
  "Pseudokirchneriella subspicata", "Pseudokirchneriella subcapitata",
  "Pseudokirchnella subcapitata", "Pseudokirchneriella subcapitata",
  "Pseudokichneriella subcapitata", "Pseudokirchneriella subcapitata",
  "S. subspicatus", "Desmodesmus subspicatus",
  "D. subspicatus", "Desmodesmus subspicatus",
  "Scenedesmus subcapitata", "Desmodesmus subspicatus",
  "Harlequin fly", "Chironomus riparius",
  "Daggerblade grass Shrimp", "Palaemonetes pugio",
  "Zebra fish", "Danio rerio",
  "Danio rerio (embryo)", "Danio rerio",
  "Common carp", "Cyprinus carpio",
  "Bluegill", "Lepomis macrochirus",
  "Fathead minnow", "Pimephales notatus",
  "Channel catfish", "Ictalurus punctatus",
  "Rainbow trout", "Oncorhynchus mykiss",
  "Sheepshead minnow", "Cyprinodon variegatus",
  "Brown trout", "Salmo trutta",
  "Great pond snail", "Lymnaea stagnalis",
  "Red seabream", "Pagrus major",
  "Dungeness crab", "Metacarcinus magister",
  "American flag fish", "Jordanella floridae",
  "Brook trout", "Salvelinus fontinalis",
  "Ide", "Leuciscus idus",
  "Louisiana crayfish", "Procambarus clarkii",
  "Atlantic salmon", "Salmo salar",
  "American waterweed (Pondweed) (live plants)", "Elodea canadensis",
  "Common hornwort (live plants)", "Ceratophyllum demersum",
  "Green cabomba (live plants)", "Cabomba caroliniana",
  "Wild celery (water celery) (live plants)", "Vallisneria americana",
  "European perch", "Perca fluviatilis",
  "Inland silverside", "Menidia beryllina",
  "Northern quahog", "Mercenaria mercenaria",
  "Mosquitofish", "Gambusia holbrooki",
  "Three-spined stickleback", "Gasterosteus aculeatus",
  "Mozambique tilapia", "Oreochromis mossambicus",
  "Spot croaker", "Leiostomus xanthurus",
  "Floating sweet-grass", "Glyceria fluitans",
  "Xenopis laevis" , "Xenopus laevis",
  "Leuciscus idus melanotu", "Leuciscus idus",
  "Pseodokirchneriella subcapitata", "Pseudokirchneriella subcapitata",
  "Glyceria max", "Glyceria maxima",
  "Oncorhynchus mykiss (species in domain Eukaryota)", "Oncorhynchus mykiss",
  "Chaoborus","Chaoborus sp.",
  "Chironomus riparius (species in domain Eukaryota)","Chironomus riparius",
  "Catostomus commersoni","Catostomus commersonii",
  "Ostracoda sp.", "Ostracoda",
  )

