derappp_bib_aquatic_toxicity <- c(
  BibEntry(
    key = 'amisulbrom_12_vol3_b9_ecotox_february_2012_public',
    title = 'Amisulbrom DAR Volume 3 Annex B.9 public',
    series = 'Amisulbrom DAR 2012',
    bibtype = 'Report',
    institution = 'European Commission',
    author = 'Anonymous',
    type = 'Draft Assessment Report (DAR)',
    year = '2012',
    file = 'EU_DAR_dRAR/amisulbrom_12_vol3_b9_ecotox_february_2012_public'
  ),
  BibEntry(
    key = 'Captan_DAR_07_Vol_3_B9_public',
    title = 'Captan DAR Volme 3 Annex B.9_public',
    series = 'Captan DAR 2005',
    bibtype = 'Report',
    institution = 'European Commission',
    author = 'Anonymous',
    type = 'Draft Assessment Report (DAR)',
    year = '2005',
    file = 'EU_DAR_dRAR/Captan_DAR_2005/Captan_DAR_07_Vol 3_B9_public',
  ),
  BibEntry(
    key = 'Tebuconazole_DAR_12_Vol3_B9_part2_public',
    title = 'Tebuconazole DAR Volume 3 Annex B.9 part2 public',
    series = 'Tebuconazole DAR 2007',
    bibtype = 'Report',
    institution = 'European Commission',
    author = 'Anonymous',
    type = 'Draft Assessment Report (DAR)',
    year = '2007',
    file = 'EU_DAR_dRAR/Tebuconazole_DAR_2007/Tebuconazole_DAR_12_Vol3_B9_part2_public.pdf',
  ),
NULL)
