derappp_bib_aquatic_toxicity <- c(
  BibEntry(
    key = 'amisulbrom_12_vol3_b9_ecotox_february_2012_public',
    title = 'Amisulbrom DAR Volume 3 Annex B.9 public',
    series = 'Amisulbrom DAR 2012',
    bibtype = 'Report',
    institution = 'European Commission',
    author = 'Anonymous',
    type = 'Draft Assessment Report (DAR)',
    year = '2012',
    file = 'EU_DAR_dRAR/amisulbrom_12_vol3_b9_ecotox_february_2012_public'
  ),
  BibEntry(
    key = 'boscalid_RAR_22_LoEP_2018-11-09',
    title = 'Boscalid RAR LoEP',
    series = 'Boscalid RAR 2018',
    bibtype = 'Report',
    institution = 'European Commission',
    author = 'Anonymous',
    type = 'Draft Assessment Report (DAR)',
    year = '2018',
    file = 'EU_DAR_dRAR/Boscalid_RAR_2018/boscalid_RAR_22_LoEP_2018-11-09',
  ),
  BibEntry(
    key = 'Captan_DAR_07_Vol_3_B9_public',
    title = 'Captan DAR Volume 3 Annex B.9 public',
    series = 'Captan DAR 2005',
    bibtype = 'Report',
    institution = 'European Commission',
    author = 'Anonymous',
    type = 'Draft Assessment Report (DAR)',
    year = '2005',
    file = 'EU_DAR_dRAR/Captan_DAR_2005/Captan_DAR_07_Vol 3_B9_public',
  ),
  BibEntry(
    key = 'Folpet_DAR_07_Vol_3_B9_public',
    title = 'Folpet DAR Volume 3 Annex B.9 public',
    series = 'Folpet DAR 2005',
    bibtype = 'Report',
    institution = 'European Commission',
    author = 'Anonymous',
    type = 'Draft Assessment Report (DAR)',
    year = '2005',
    file = 'EU_DAR_dRAR/Folpet_DAR_2005/Folpet_DAR_07_Vol_3_B9_public',
  ),
  BibEntry(
    key = 'Tebuconazole_DAR_12_Vol3_B9_part2_public',
    title = 'Tebuconazole DAR Volume 3 Annex B.9 part2 public',
    series = 'Tebuconazole DAR 2007',
    bibtype = 'Report',
    institution = 'European Commission',
    author = 'Anonymous',
    type = 'Draft Assessment Report (DAR)',
    year = '2007',
    file = 'EU_DAR_dRAR/Tebuconazole_DAR_2007/Tebuconazole_DAR_12_Vol3_B9_part2_public.pdf',
  ),
    BibEntry(
    key = 'Sulphur_RAR_11_Volume_3CA_B-9_2022-08_sanitised',
    title = 'Sulphur RAR 11 Volume 3CA B9 2022-08 sanitised',
    series = 'Sulphur RAR 2022',
    bibtype = 'Report',
    institution = 'European Commission',
    author = 'Anonymous',
    type = 'Draft Renewal Assessment Report (RAR)',
    year = '2022',
    file = 'EU_DAR_dRAR/Sulfur_RAR_revised_2022/Sulphur_RAR_11_Volume_3CA_B-9_2022-08_sanitised.pdf',
  ),
  BibEntry(
    key = 'Sulphur_DAR_2008_11_Vol3_B9_public',
    title = 'Sulphur DAR 2008 11 Vol3 B9 public',
    series = 'Sulphur DAR 2008',
    bibtype = 'Report',
    institution = 'European Commission',
    author = 'Anonymous',
    type = 'Draft Assessment Report (DAR)',
    year = '2008',
    file = 'EU_DAR_dRAR/Sulphur_DAR_2008/Sulphur_DAR_2008_11_Vol3_B9_public.pdf',
  ),
NULL)
